# Generated by Django 4.2.20 on 2025-07-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storePage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pImage",
        ),
    ]
