# Generated by Django 4.2.20 on 2025-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storePage", "0002_remove_product_pimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pImage",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="pDescription",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="pName",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="pPrice",
            field=models.IntegerField(null=True),
        ),
    ]
