# Generated by Django 4.2.20 on 2025-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storePage", "0003_product_pimage_alter_product_pdescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pImage",
            field=models.ImageField(blank=True, null=True, upload_to="products_image/"),
        ),
    ]
