# Generated by Django 4.2.20 on 2025-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storePage", "0004_alter_product_pimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="products_images/"
            ),
        ),
    ]
