# Generated by Django 4.2.20 on 2025-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storePage", "0005_alter_product_pimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pImage",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
