# Generated by Django 4.2.20 on 2025-07-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("storename", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp", models.IntegerField()),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
