# Generated by Django 4.2.20 on 2025-07-14 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storeAdmin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storemanager",
            name="email",
        ),
        migrations.RemoveField(
            model_name="storemanager",
            name="password",
        ),
        migrations.RemoveField(
            model_name="storemanager",
            name="username",
        ),
        migrations.AddField(
            model_name="storemanager",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storemanager",
            name="whatsapp",
            field=models.CharField(max_length=15),
        ),
    ]
