# Generated by Django 4.2.20 on 2025-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeAdmin", "0003_remove_storemanager_name_remove_storemanager_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemanager",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
