# Generated by Django 4.2.20 on 2025-07-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeAdmin", "0004_storemanager_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storemanager",
            name="storename",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
