# Generated by Django 4.2.20 on 2025-07-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeAdmin", "0005_alter_storemanager_storename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storemanager",
            name="whatsapp",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
