# Generated by Django 4.2.20 on 2025-07-16 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storeAdmin", "0006_alter_storemanager_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemanager",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="storemanager",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storemanager",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="storemanager",
            name="whatsapp",
            field=models.IntegerField(null=True),
        ),
    ]
